### ISSUE TITLE
Get account type from LinkSuccess

### ISSUE THREAD

**Issue by shalbert94** [plaid/plaid-link-android#124]
# The problem
The [Link documentation](https://plaid.com/docs/link/android/#onsuccess) says it is possible to extract each account's `type`, but the generated class doesn't have it. There is a `subtype`, but what I want is the `type`. 

# Environment

`implementation "com.plaid.link:sdk-core:3.1.1"`

# Steps to Reproduce

Open the [Link documentation](https://plaid.com/docs/link/android/#onsuccess), and you will see `metadata` -> `accounts` -> `type`.

Now, open `com.plaid.link.result.LinkAccount` and you will see that `type` is not an option

# Expected Result
`type` should be a property in `com.plaid.link.result.LinkAccount`.

**Comment by shalbert94** [comment]
Ah, so `accountType` is accessed as a property of `subtype`. That was surprising since the documentation indicates it will be accessible at the same level as `subType`

**Comment by JeroenMols** [comment]
Thanks for reporting @shalbert94 and I'm glad you already figured it out.

Because our public API allows to define a `AccountSubtype` filter when opening Link, the subtype is the main property which has an implicitly linked `AccountType` to it. I'll make sure to update our docs to reflect that better.
