### ISSUE TITLE
Build issue:  Conflicts with Firebase perf dependency

### ISSUE THREAD

**Issue by lokeshbhattarai** [plaid/plaid-link-android#169]
# The problem

I'm running into build error when running Plaid Link SDK in the existing project which uses Firebase Performance library.

Here's is the build error I see 

```
2 files found with path 'google/protobuf/field_mask.proto'
```

It seems Plaid uses https://github.com/streem/pbandk which ships  it's own `.proto` artifacts .

I'm facing this issue with `3.3.1` version . Apparently the issue doesn't happen on `3.3.0` version.

# Environment

|                        |  |
| ------------------------| ---------- |
| Android OS Version                    | API 30             |
| Android Devices/Emulators    |  Pixel 4a emulator                |

# Steps to Reproduce

1. Create new project and add Firebase performance library.
2. Add dependency to plaid link `3.3.1` version. 
3. Build project. 

# Logs
Any relevant logs from Android Logcat or the iOS console including stacktraces.
```
Execution failed for task ':app:mergeDebugJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
   > 2 files found with path 'google/protobuf/field_mask.proto' from inputs:
      - /Users/<user>/.gradle/caches/transforms-3/fa0da1f0c8de41719ef386f1d79ae365/transformed/jetified-pbandk-protos-0.10.0.jar
      - /Users/<user>/.gradle/caches/transforms-3/b2b785f9ac38d978e20c74519617e8df/transformed/jetified-protobuf-javalite-3.14.0.jar
```

# Code To Reproduce Issue

Gradle config for new project.

root gradle

```
 dependencies {
     // ...
        classpath "com.google.firebase:perf-plugin:1.4.0"
    }
```

app module gradle

```
plugins {
    id 'com.android.application'
    id 'com.google.firebase.firebase-perf'
    //...
}

dependencies { 
    implementation platform('com.google.firebase:firebase-bom:28.0.1')
    implementation("com.google.firebase:firebase-perf-ktx")
    
    implementation("com.plaid.link:sdk-core:3.3.1") // no build issues with 3.3.0
}

```

**Comment by JeroenMols** [comment]
Thank you for reporting this issue!

This issue is caused because the Plaid Link SDK uses protocol buffers internally. But sadly there are different variants of the protocol buffers dependency and some libraries (such as Firebase) aren't using the Android optimized variant causing conflicts. (see for instance https://github.com/plaid/plaid-link-android/issues/145)

In order to structurally fix these conflicts, we've helped migrate our transitive dependency `pbandk` away from using the protocol buffer dependencies altogether. This fixed all possible runtime conflicts, but broken their Gradle plugin to generate kotlin models for `.proto` files.

To fix the latter problem, they created a new artifact `pbandk-protos` that contains those `.proto` files. Unfortunately this means that both `protobuf-javalite` (from `firebase-per-ktx`) and `pbandk-protos` (from our SDK) contain the same `.proto` files breaking your build.

The short term fix would be to add the following to your `build.gradle` file:

```kotlin
android {
    packagingOptions {
        exclude 'google/protobuf/*.proto'
    }
}
```

This is safe to do, as the `.proto` files are only part of the artifacts to make the protobuf generator Gradle plugin work, they aren't used at runtime.

I've filed an issue with `pbandk` https://github.com/streem/pbandk/issues/157 and we'll fix this structurally in a future release.

Could you please let me know whether that works?

**Comment by lokeshbhattarai** [comment]
Adding packaging option to remove proto files seems to have fixed the issue for me. 


Note if  anyone else runs into this: 
 I'm using Plaid dependency in my library module and not in app module. However I had to add the packaging option to my app module to get this work.
 
 // app module gradle
 
 ```
 android {
     packagingOptions {
         resources.excludes.add("google/protobuf/*.proto")
     }
  }
 ```
 
 Since the workaround does work, I'm closing the issue. Hopefully we won't need this workaround in future releases.
 
 Thank you.

**Comment by JeroenMols** [comment]
Glad to hear that this resolves your issue @lokeshbhattarai!

Thanks again for reporting this issue! And yes, we will make sure to have a structural fix for this in the next release.
