### ISSUE TITLE
onActivityResult not called on android SDK v1.4.1

### ISSUE THREAD

**Issue by waseem786** [plaid/plaid-link-android#65]
Hi, 
I have a problem with linking a bank account with Plaid, I set up all the configuration according to the Plaid documentation [this](https://plaid.com/docs/link/android/)
After configure I can link a bank successfully up to link bank success screen.
But, when the press continue button from success screen, `onActivityResult()` method should fire according to the documentation. But nothing happens on my code, just dismiss the link bank success screen.
Below I attached my codes, 

**config in the Application class**
![plaid_config](https://user-images.githubusercontent.com/8718988/82927631-9e6fd600-9f9e-11ea-8312-8d7074411584.PNG)

**Button click event for link bank**
![plaid_button](https://user-images.githubusercontent.com/8718988/82927710-be9f9500-9f9e-11ea-96a3-a3eee389d81b.PNG)

**onActivityResult to handle result**
![plaid_result](https://user-images.githubusercontent.com/8718988/82927804-e262db00-9f9e-11ea-8429-12731fcdba21.PNG)

Note: I figured that onActivityResult not working by using logs shown on the last image. That means I did not see any log printed on the Logcat.

**Comment by zsweigart** [comment]
Hi @waseem786, thanks for reaching out.  It seems your `onActivityResult` is not being called because you are passing in `requireActivity`.  Instead open with `Plaid.openLink(this, ...)`

**Comment by waseem786** [comment]
@zsweigart thank you for save me. it worked :)
But, I am using the above functions in a fragment, then still why I need to use `this` instead of `requireActivity` ?

**Comment by zsweigart** [comment]
If you call `startActivityForResult` with an `activity` parameter, the result will be returned to the parent activity.  If you instead pass a `fragment` parameter in, the result will be returned to the fragment.  One thing to watch out for is if you pass a `fragment` parameter and your host activity overrides `onActivityResult` you have to make sure you call `super` in the override function (it's usually best in this case to call super as the first statement in the function) otherwise the activity could still consume it.  If you're interested I suggest reading through the source code of `FragmentActivity`
