### ISSUE TITLE
Caused by java.lang.RuntimeException with proguard rules enabled.

### ISSUE THREAD

**Issue by snehas13** [plaid/plaid-link-android#76]
Hi,

We are using plaid version 1.4.0 in our project and it works fine for debug builds.
But for release build when we enable proguard rules then we get below runtime exception.

We also use Tink library 1.3.0 version in our project for encryption and decryption.
Below exception is coming in the screen where we initialise Tink Library.

Caused by java.lang.RuntimeException
Field configName_ for c.b.c.a.j0.a3 not found. Known fields are [private com.google.crypto.tink.shaded.protobuf.Internal$i c.b.c.a.j0.a3.e, private static final c.b.c.a.j0.a3 c.b.c.a.j0.a3.f, private static volatile com.google.crypto.tink.shaded.protobuf.x0 c.b.c.a.j0.a3.g]

W.r.to initialization of Tink library we are following exact code mentioned in the Overview of below link.
https://github.com/google/tink

Request you to help us on this issue.

**Comment by JeroenMols** [comment]
Thanks for reporting! We are to reproduce a similar issue and are investigating what the cause might be.

**Comment by JeroenMols** [comment]
Hi @snehas13 ,

Our SDK relies on Tink library version `1.4.0-rc2` and we suspect that this transitive dependency is causing your app to also use Tink version `1.4.0-rc2` instead of `1.3.0`.

After some investigation we found that:

- Tink bundles (e.g. copies in) protobuf to avoid dependency conflicts
- A newer Protobuf version (included in Tink 1.4.x) relies on reflection
- Tink 1.4.0-RC2 doesn’t include the required Proguard configuration to avoid the reflection from breaking.
- See bug here: https://github.com/google/tink/issues/361

To verify that this is indeed the case, could you try adding the following configuration to your Proguard file and let us know if that solves your problem?

```
-keepclassmembers class * extends com.google.crypto.tink.shaded.protobuf.GeneratedMessageLite {
  <fields>;
}
```

**Comment by snehas13** [comment]
The given solution works :) Thanks a lot for the help.

**Comment by JeroenMols** [comment]
Thanks for verifying that, our next SDK release 2.0.0 will have these rules bundled in (for your convenience), once we are able to upgrade to Tink 1.4.0 we will do so and remove these rules.

You can preview that SDK version here: https://bintray.com/plaid/link-android/com.plaid.link/2.0.0-rc3
Note that we don't have an upgrade guide published yet, but we will do so as soon as we'll release 2.0.0 stable.
